Fast reboot: check if the files are present before accessing (#1526)
[201811] On some old images, some of the executables are not present. Therefore, when latest fast-reboot script is used, it will lead to failures.
In this change, add checks to test if below files exist and are executable, before executing them.
/usr/bin/asic_config_check
/usr/bin/filter_fdb_entries

diff --git a/scripts/fast-reboot b/scripts/fast-reboot
--- a/scripts/fast-reboot
+++ b/scripts/fast-reboot
@@ -283,18 +283,20 @@ function reboot_pre_check()
     fi
     
     # Make sure ASIC configuration has not changed between images
-    ASIC_CONFIG_CHECK_SCRIPT="/usr/bin/asic_config_check"
-    ASIC_CONFIG_CHECK_SUCCESS=0
-    if [[ "$REBOOT_TYPE" = "warm-reboot" || "$REBOOT_TYPE" = "fastfast-reboot" ]]; then
-        ASIC_CONFIG_CHECK_EXIT_CODE=0
-        ${ASIC_CONFIG_CHECK_SCRIPT} || ASIC_CONFIG_CHECK_EXIT_CODE=$?
+    if [[ -x /usr/bin/asic_config_check ]]; then
+        ASIC_CONFIG_CHECK_SCRIPT="/usr/bin/asic_config_check"
+        ASIC_CONFIG_CHECK_SUCCESS=0
+        if [[ "$REBOOT_TYPE" = "warm-reboot" || "$REBOOT_TYPE" = "fastfast-reboot" ]]; then
+            ASIC_CONFIG_CHECK_EXIT_CODE=0
+            ${ASIC_CONFIG_CHECK_SCRIPT} || ASIC_CONFIG_CHECK_EXIT_CODE=$?
 
-        if [[ "${ASIC_CONFIG_CHECK_EXIT_CODE}" != "${ASIC_CONFIG_CHECK_SUCCESS}" ]]; then
-            if [[ x"${FORCE}" == x"yes" ]]; then
-                debug "Ignoring ASIC config checksum failure..."
-            else
-                error "ASIC config may have changed: errno=${ASIC_CONFIG_CHECK_EXIT_CODE}"
-                exit "${EXIT_FAILURE}"
+            if [[ "${ASIC_CONFIG_CHECK_EXIT_CODE}" != "${ASIC_CONFIG_CHECK_SUCCESS}" ]]; then
+                if [[ x"${FORCE}" == x"yes" ]]; then
+                    debug "Ignoring ASIC config checksum failure..."
+                else
+                    error "ASIC config may have changed: errno=${ASIC_CONFIG_CHECK_EXIT_CODE}"
+                    exit "${EXIT_FAILURE}"
+                fi
             fi
         fi
     fi
@@ -395,14 +397,15 @@ if [[ "$REBOOT_TYPE" = "fast-reboot" ]]; then
         unload_kernel
         exit "${EXIT_FAST_REBOOT_DUMP_FAILURE}"
     fi
-
-    FILTER_FDB_ENTRIES_RC=0
-    # Filter FDB entries using MAC addresses from ARP table
-    /usr/bin/filter_fdb_entries -f $DUMP_DIR/fdb.json -a $DUMP_DIR/arp.json -c $CONFIG_DB_FILE || FILTER_FDB_ENTRIES_RC=$?
-    if [[ FILTER_FDB_ENTRIES_RC -ne 0 ]]; then
-        error "Failed to filter FDb entries. Exit code: $FILTER_FDB_ENTRIES_RC"
-        unload_kernel
-        exit "${EXIT_FILTER_FDB_ENTRIES_FAILURE}"
+    if [[ -x /usr/bin/filter_fdb_entries ]]; then
+       FILTER_FDB_ENTRIES_RC=0
+       # Filter FDB entries using MAC addresses from ARP table
+       /usr/bin/filter_fdb_entries -f $DUMP_DIR/fdb.json -a $DUMP_DIR/arp.json -c $CONFIG_DB_FILE || FILTER_FDB_ENTRIES_RC=$?
+       if [[ FILTER_FDB_ENTRIES_RC -ne 0 ]]; then
+           error "Failed to filter FDb entries. Exit code: $FILTER_FDB_ENTRIES_RC"
+           unload_kernel
+           exit "${EXIT_FILTER_FDB_ENTRIES_FAILURE}"
+       fi
     fi
 fi
 
